apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opf-datacatalog
spec:
  destination:
    namespace: opf-datacatalog
    name: in-cluster
  project: operate-first
  source:
    path: odh/base/datacatalog
    repoURL: https://github.com/operate-first/apps.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - Validate=false
