apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opf-kafka
spec:
  destination:
    namespace: opf-kafka
    name: in-cluster
  project: operate-first
  source:
    path: base/kafka
    repoURL: https://github.com/operate-first/odh.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - Validate=falsex
