apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opf-odh-operator
spec:
  destination:
    namespace: opf-odh-operator
    name: in-cluster
  project: operate-first
  source:
    path: odh/overlays/crc/operator
    repoURL: https://github.com/operate-first/apps.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - Validate=false
