---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mailing-list-analysis-toolkit
spec:
  destination:
    name: moc-cnv
    namespace: opf-argo
  project: data-science
  source:
    path: manifests
    repoURL: https://github.com/aicoe-aiops/mailing-list-analysis-toolkit.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
