---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-logging
spec:
  destination:
    name: moc-cnv
  source:
    path: cluster-logging/overlays/moc/
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
