---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-resources
spec:
  source:
    path: cluster-scope/overlays/moc/
  ignoreDifferences:
    - group: imageregistry.operator.openshift.io
      kind: Config
      name: cluster
      version: v1
      jsonPointers:
        - /spec/defaultRoute
        - /spec/httpSecret
        - /spec/proxy
        - /spec/requests
        - /spec/rolloutStrategy
