---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opf-jupyterhub
spec:
  destination:
    name: moc-cnv
    namespace: opf-jupyterhub
  project: operate-first
  source:
    path: odh/overlays/moc/zero/jupyterhub
    repoURL: https://github.com/operate-first/apps.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
