---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opf-kfdefs
spec:
  destination:
    name: zero
    namespace: opendatahub
  project: operate-first
  source:
    path: kfdefs/overlays/moc/zero
    repoURL: https://github.com/operate-first/apps.git
    targetRevision: HEAD
